name: Bind City (Manual)

on:
  workflow_dispatch:

jobs:
  send_bind_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Send binding email
        run: python bind_city.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          FROM_USER: ${{ secrets.FROM_USER }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
