name: Daily Weather Task

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  daily_weather_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch Replies and Update Mapping
        run: python fetch_replies.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          FROM_USER: ${{ secrets.FROM_USER }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      - name: Send Weather to Bound Emails
        run: python send_weather.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          FROM_USER: ${{ secrets.FROM_USER }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        run: |
          git add email_city_map.json
          git commit -m "Update email-city mapping [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
